parameters:
  plugin.table.prefix: "smartcat_connector_"
  plugin.options:
    #Данные к доступу к api (отображаются)
    - "smartcat_api_login"
    - "smartcat_api_password"
    - "smartcat_api_server"
    #Additional params (отображаются)
    - "smartcat_debug_mode"
    #Признак активации ручного обновления статистики
    - "statistic_queue_active"
    #Авторизационный код для callback
    - "callback_authorisation_token"
